export enum AuditLog {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  ASSIGN_USER = 'ASSIGN_USER',
  UNASSIGN_USER = 'UNASSIGN_USER',
  ADD_USER = 'ADD_USER',
  REMOVE_USER = 'REMOVE_USER',
  ADD_STRUCTURE = 'ADD_STRUCTURE',
  REMOVE_STRUCTURE = 'REMOVE_STRUCTURE',
}

export const AuditLogLabels = {
  [AuditLog.CREATE]: 'Création',
  [AuditLog.UPDATE]: 'Modification',
  [AuditLog.DELETE]: 'Suppression',
  [AuditLog.ASSIGN_USER]: 'Assignation d’utilisateur',
  [AuditLog.UNASSIGN_USER]: 'Désassignation d’utilisateur',
  [AuditLog.ADD_USER]: 'Ajout d’utilisateur à la structure',
  [AuditLog.REMOVE_USER]: 'Retrait d’utilisateur de la structure',
  [AuditLog.ADD_STRUCTURE]: 'Ajout de structure',
  [AuditLog.REMOVE_STRUCTURE]: 'Suppression de structure',
};

// export enum AuditLogValue {
//   // Champs de Role
//   role = 'role',

//   // Champs de Structure
//   structureId = 'structureId',
//   structureName = 'structureName',
//   structureType = 'structureType',
//   structureService = 'structureService',
//   structureEmail = 'structureEmail',
//   structurePhone = 'structurePhone',
//   structureAddressId = 'structureAddressId',

//   // Champs de Address
//   addressId = 'addressId',
//   addressCountry = 'addressCountry',
//   addressPostcode = 'addressPostcode',
//   addressCity = 'addressCity',
//   addressStreetL1 = 'addressStreetL1',
//   addressStreetL2 = 'addressStreetL2',
//   addressLongitude = 'addressLongitude',
//   addressLatitude = 'addressLatitude',

//   // Champs de User
//   userId = 'userId',
//   userFirstname = 'userFirstname',
//   userLastname = 'userLastname',
//   userLogin = 'userLogin',
//   userPassword = 'userPassword',
//   userEmail = 'userEmail',
//   userPhone = 'userPhone',
//   userAddressId = 'userAddressId',

//   // Champs de Ticket
//   ticketId = 'ticketId',
//   ticketTitle = 'ticketTitle',
//   ticketDescription = 'ticketDescription',
//   ticketCreatedAt = 'ticketCreatedAt',
//   ticketUpdatedAt = 'ticketUpdatedAt',
//   ticketArchivedAt = 'ticketArchivedAt',
//   ticketStatus = 'ticketStatus',
//   ticketPriority = 'ticketPriority',
//   ticketCategory = 'ticketCategory',
//   ticketAssignedUsers = 'ticketAssignedUsers',
//   ticketAuthorId = 'ticketAuthorId',

//   // Champs de Comment
//   commentId = 'commentId',
//   commentContent = 'commentContent',
//   commentCreatedAt = 'commentCreatedAt',
//   commentUpdatedAt = 'commentUpdatedAt',
//   commentReadAt = 'commentReadAt',
//   commentTicketId = 'commentTicketId',
//   commentAuthorId = 'commentAuthorId',

//   // Champs de AuditLog
//   auditLogId = 'auditLogId',
//   auditLogUserId = 'auditLogUserId',
//   auditLogLinkedId = 'auditLogLinkedId',
//   auditLogLinkedTable = 'auditLogLinkedTable',
//   auditLogAction = 'auditLogAction',
//   auditLogFields = 'auditLogFields',
//   auditLogModificationDate = 'auditLogModificationDate',
// }
// export const AuditLogValueLabels = {
//   [AuditLogValue.role]: 'Rôle',
//   [AuditLogValue.structureId]: 'ID de la Structure',
//   [AuditLogValue.structureName]: 'Nom de la structure',
//   [AuditLogValue.structureType]: 'Type de la structure',
//   [AuditLogValue.structureService]: 'Service de la structure',
//   [AuditLogValue.structureEmail]: 'Adresse email de la structure',
//   [AuditLogValue.structurePhone]: 'N° de téléphone de la structure',
//   [AuditLogValue.structureAddressId]: 'Adresse de la structure',
//   [AuditLogValue.addressId]: 'ID de l’adresse',
//   [AuditLogValue.addressCountry]: 'Pays',
//   [AuditLogValue.addressPostcode]: 'Code postal',
//   [AuditLogValue.addressCity]: 'Ville',
//   [AuditLogValue.addressStreetL1]: 'Rue 1',
//   [AuditLogValue.addressStreetL2]: 'Rue 2',
//   [AuditLogValue.addressLongitude]: 'Longitude',
//   [AuditLogValue.addressLatitude]: 'Latitude',
//   [AuditLogValue.userId]: 'ID de l’utilisateur',
//   [AuditLogValue.userFirstname]: 'Présnom',
//   [AuditLogValue.userLastname]: 'Nom',
//   [AuditLogValue.userLogin]: 'Login',
//   [AuditLogValue.userPassword]: 'Mot de passe',
//   [AuditLogValue.userEmail]: 'Adresse email',
//   [AuditLogValue.userPhone]: 'N° de téléphone',
//   [AuditLogValue.userAddressId]: 'Adresse de l’utilisateur',
//   [AuditLogValue.ticketId]: 'ID du ticket',
//   [AuditLogValue.ticketTitle]: 'Titre du ticket',
//   [AuditLogValue.ticketDescription]: 'Description du ticket', 
//   [AuditLogValue.ticketCreatedAt]: 'Date de création du ticket',
//   [AuditLogValue.ticketUpdatedAt]: 'Date de mise à jour du ticket',
//   [AuditLogValue.ticketArchivedAt]: 'Date d’archive du ticket',
//   [AuditLogValue.ticketStatus]: 'Statut du ticket', 
//   [AuditLogValue.ticketPriority]: 'Priorité du ticket',
//   [AuditLogValue.ticketCategory]: 'Catégorie du ticket',  
//   [AuditLogValue.ticketAssignedUsers]: 'Utilisateurs assignés au ticket',
//   [AuditLogValue.ticketAuthorId]: 'Auteur du ticket', 
//   [AuditLogValue.commentId]: 'ID du commentaire',
//   [AuditLogValue.commentContent]: 'Contenu du commentaire',
//   [AuditLogValue.commentCreatedAt]: 'Date de création du commentaire',
//   [AuditLogValue.commentUpdatedAt]: 'Date de mise à jour du commentaire',
//   [AuditLogValue.commentReadAt]: 'Date de lecture du commentaire',
//   [AuditLogValue.commentTicketId]: 'Ticket auquel le commentaire est attaché',
//   [AuditLogValue.commentAuthorId]: 'Auteur du commentaire',
//   [AuditLogValue.auditLogAction]: 'Action',
//   [AuditLogValue.auditLogFields]: 'Champs',
//   [AuditLogValue.auditLogModificationDate]: 'Date de modification',
// }