name: CI/CD for Frontend

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushes à la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Récupérer le code source depuis le dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Construire l'image Docker pour le frontend
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tickly-frontend:latest -f .github/workflows/Dockerfile .

      # Étape 3: Se connecter à Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Étape 4: Pousser l'image Docker sur Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tickly-frontend:latest

      # Étape 5: Installer sshpass
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Étape 6: Déployer sur le VPS
      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            # Stopper et supprimer l'ancien conteneur frontend
            docker stop tickly-frontend || true
            docker rm tickly-frontend || true

            # Démarrer le nouveau conteneur
            docker run -d --name tickly-frontend --network tickly_default -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/tickly-frontend:latest
          EOF# Démarrer un nouveau container avec la nouvelle image
            docker run -d --name tickly-frontend --network tickly_default -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/tickly-frontend:latest
          EOF

      # Étape 7: Vérifier l'état du container sur le VPS
      - name: Check Docker container status
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "docker ps | grep tickly-frontend"
